language: python
sudo: required
python:
  - "3.5"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
script:
  - coverage run Tides/test.py
  - coverage report -m Tides/tc.py Tides/test.py