language: python
sudo: required
python:
  - "3.5"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
script:
  - coverage run test.py
  - coverage report -m tc.py test.py tides.py